version: '3.7'
services:
  pybill:
    build:
      context: .
      target: development
    image: pybill
    ports:
      - "8000:8000"
    volumes:
      - .:/code/
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pybill
      POSTGRES_PASSWORD: pybill
      POSTGRES_DB: pybill
