version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        enviromnet:
          DATABASE_URL: postgresql://olist@localhost/olist

      - image: circleci/postgres:alpine
        environment:
          POSTGRES_USER: olist
          POSTGRES_DB: olist

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: sudo apt-get update && apt-get install -y gcc postgresql-dev zlib-dev jpeg-dev libxml2-dev libxslt-dev

      - run:
          name: Install requirements
          command: pip install --upgrade pip && pip install --no-cache-dir --requirement requirements/development.txt

  test:
    docker:
      - image: circleci/python:3.7
        enviromnet:
          DATABASE_URL: postgresql://olist@localhost/olist

      - image: circleci/postgres:alpine
        environment:
          POSTGRES_USER: olist
          POSTGRES_DB: olist

    steps:
      - checkout
      - run:
          name: Linter
          command: pycodestyle

      - run:
          name: Unit tests
          command: python manage.py test --verbosity 2 --noinput  tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
