version:2
jobs:
  build:
    docker:
      - image: circleci/python:3-alpine

      - image: circleci/postgres:alpine
        environment:
          POSTGRES_USER: olist
          POSTGRES_DB: olist

    steps:
      - checkout

      - run:
        name: Install dependencies
        command: apk add --no-cache gcc musl-dev postgresql-dev zlib-dev jpeg-dev libxml2-dev libxslt-dev

      - run:
        name: Install requirements
        command: pip install --upgrade pip && pip install --no-cache-dir --requirement requirements/development.txt

      - run:
        name: Linter
        command: pycodestyle

      - run:
        name: Unit tests
        command: python manage.py test --verbosity 2 --noinput  tests
