version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        enviromnet:
          DATABASE_URL: postgresql://olist@localhost/olist

      - image: circleci/postgres:alpine
        environment:
          POSTGRES_USER: olist
          POSTGRES_DB: olist

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Install dependencies
          command: apk add --no-cache gcc musl-dev postgresql-dev zlib-dev jpeg-dev libxml2-dev libxslt-dev

      - run:
          name: Install requirements
          command: pip install --upgrade pip && pip install --no-cache-dir --requirement requirements/development.txt

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"

  test:
    docker:
      - image: circleci/python:3.7
        enviromnet:
          DATABASE_URL: postgresql://olist@localhost/olist

      - image: circleci/postgres:alpine
        environment:
          POSTGRES_USER: olist
          POSTGRES_DB: olist

    steps:
      - checkout
      - run:
          name: Linter
          command: pycodestyle

      - run:
          name: Unit tests
          command: python manage.py test --verbosity 2 --noinput  tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
