# Generated by Django 2.2.2 on 2019-06-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Start record'), (1, 'End record')])),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.CharField(max_length=256)),
                ('source', models.CharField(blank=True, max_length=11)),
                ('destination', models.CharField(blank=True, max_length=11)),
            ],
            options={
                'unique_together': {('type', 'call_id')},
            },
        ),
    ]
