# Generated by Django 2.2.2 on 2019-06-20 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='end_record',
            field=models.ForeignKey(help_text='The end record of the pair', on_delete=django.db.models.deletion.CASCADE, related_name='end_record_bill', to='calls.CallRecord'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='The bill price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='start_record',
            field=models.ForeignKey(help_text='The start record of the pair', on_delete=django.db.models.deletion.CASCADE, related_name='start_record_bill', to='calls.CallRecord'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='call_id',
            field=models.CharField(help_text='Unique id for each call record pair', max_length=256),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='destination',
            field=models.CharField(blank=True, help_text='The phone number receiving the call (required on start record)', max_length=11),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='source',
            field=models.CharField(blank=True, help_text='The subscriber phone number that originated the call (required on start record)', max_length=11),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='timestamp',
            field=models.DateTimeField(help_text='The timestamp of when the event occured'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='type',
            field=models.IntegerField(choices=[(0, 'Start record'), (1, 'End record')], help_text='Indicate if it\'s a call "start" or "end" record'),
        ),
    ]
