# Generated by Django 2.2.2 on 2019-06-20 00:24
from django.db import migrations
from django.utils import dateparse
from olist.calls.models import CallRecord


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    records = [
        {
            'type': CallRecord.START_RECORD,
            'call_id': 70,
            'source': '99988526423',
            'destination': '9933468278',
            'timestamp': dateparse.parse_datetime('2016-02-29T12:00:00Z'),
        },
        {
            'type': CallRecord.END_RECORD,
            'call_id': 70,
            'timestamp': dateparse.parse_datetime('2016-02-29T14:00:00Z')
        },
        {
            'type': CallRecord.START_RECORD,
            'call_id': 71,
            'source': '99988526423',
            'destination': '9933468278',
            'timestamp': dateparse.parse_datetime('2017-12-11T15:07:13Z'),
        },
        {
            'type': CallRecord.END_RECORD,
            'call_id': 71,
            'timestamp': dateparse.parse_datetime('2017-12-11T15:14:56Z')
        },
        {
            'type': CallRecord.START_RECORD,
            'call_id': 72,
            'source': '99988526423',
            'destination': '9933468278',
            'timestamp': dateparse.parse_datetime('2017-12-12T22:47:56Z'),
        },
        {
            'type': CallRecord.END_RECORD,
            'call_id': 72,
            'timestamp': dateparse.parse_datetime('2017-12-12T22:50:56Z')
        },
        {
            'type': CallRecord.START_RECORD,
            'call_id': 73,
            'source': '99988526423',
            'destination': '9933468278',
            'timestamp': dateparse.parse_datetime('2017-12-12T21:57:13Z'),
        },
        {
            'type': CallRecord.END_RECORD,
            'call_id': 73,
            'timestamp': dateparse.parse_datetime('2017-12-12T22:10:56Z')
        },
        {
            'type': CallRecord.START_RECORD,
            'call_id': 74,
            'source': '99988526423',
            'destination': '9933468278',
            'timestamp': dateparse.parse_datetime('2017-12-12T04:57:13Z'),
        },
        {
            'type': CallRecord.END_RECORD,
            'call_id': 74,
            'timestamp': dateparse.parse_datetime('2017-12-12T06:10:56Z')
        },
        {
            'type': CallRecord.START_RECORD,
            'call_id': 75,
            'source': '99988526423',
            'destination': '9933468278',
            'timestamp': dateparse.parse_datetime('2017-12-13T21:57:13Z'),
        },
        {
            'type': CallRecord.END_RECORD,
            'call_id': 75,
            'timestamp': dateparse.parse_datetime('2017-12-14T22:10:56Z')
        },
        {
            'type': CallRecord.START_RECORD,
            'call_id': 76,
            'source': '99988526423',
            'destination': '9933468278',
            'timestamp': dateparse.parse_datetime('2017-12-12T15:07:58Z'),
        },
        {
            'type': CallRecord.END_RECORD,
            'call_id': 76,
            'timestamp': dateparse.parse_datetime('2017-12-12T15:12:56Z')
        },
        {
            'type': CallRecord.START_RECORD,
            'call_id': 77,
            'source': '99988526423',
            'destination': '9933468278',
            'timestamp': dateparse.parse_datetime('2018-02-28T21:57:13Z'),
        },
        {
            'type': CallRecord.END_RECORD,
            'call_id': 77,
            'timestamp': dateparse.parse_datetime('2018-03-01T22:10:56Z')
        }
    ]

    # Bulk action doesn't call signals
    for record in records:
        CallRecord.objects.using(db_alias).create(**record)


def reverse_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    CallRecord.objects.using(db_alias).filter(call_id__in=range(70, 78)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20190620_0024'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
